import { defineConfig } from 'wxt';

export default defineConfig({
  srcDir: 'src',
  outDir: '.output',
  extensionApi: 'chrome',
  modules: ['@wxt-dev/module-react'],
  manifest: {
    name: 'Tsugi - Your Watch List',
    description: 'Track anime and manga across any platform and sync to MAL, AniList, Shikimori, Bangumi',
    version: '0.1.0',
    permissions: [
      'storage',
      'tabs',
      'activeTab',
      'identity',
    ],
    icons: {
      16: '/tsugi-icon-16.png',
      32: '/tsugi-icon-32.png',
      48: '/tsugi-icon-48.png',
      128: '/tsugi-icon-128.png',
    },
    web_accessible_resources: [
      {
        resources: ['*.png', '*.svg'],
        matches: ['<all_urls>'],
      },
    ],
    action: {
      default_icon: {
        16: '/tsugi-icon-16.png',
        32: '/tsugi-icon-32.png',
      },
      default_title: 'Tsugi - Your Watch List',
    },
    host_permissions: [
      // Tracker APIs
      'https://api.myanimelist.net/*',
      'https://myanimelist.net/*',
      'https://graphql.anilist.co/*',
      'https://anilist.co/*',
      'https://shikimori.one/*',
      'https://api.bgm.tv/*',
      'https://bgm.tv/*',
      // ── Legal anime ──────────────────────────────────────────────────────
      '*://*.crunchyroll.com/*',
      '*://*.netflix.com/*',
      '*://*.hidive.com/*',
      '*://*.hulu.com/*',
      '*://*.funimation.com/*',
      '*://*.animationdigitalnetwork.com/*',
      '*://*.animeonegai.com/*',
      '*://*.animeonsen.xyz/*',
      '*://*.bilibili.tv/*',
      '*://*.proxer.me/*',
      // ── Community anime — .to / global ───────────────────────────────────
      '*://*.zoro.to/*',
      '*://*.aniwatch.to/*',
      '*://*.aniwatchtv.to/*',
      '*://*.hianime.to/*',
      '*://*.9anime.to/*',
      '*://*.9anime.me/*',
      '*://*.aniwave.to/*',
      '*://*.animesuge.to/*',
      '*://*.anicrush.to/*',
      '*://*.an1me.to/*',
      '*://*.anigo.to/*',
      '*://*.aninexus.to/*',
      '*://*.anixl.to/*',
      '*://*.kuudere.to/*',
      '*://*.miruro.to/*',
      '*://*.anidream.cc/*',
      '*://*.anoboye.com/*',
      '*://*.animekai.to/*',
      '*://*.animenosub.to/*',
      '*://*.animewho.com/*',
      '*://*.anizium.co/*',
      '*://*.fireani.me/*',
      '*://*.animetsu.net/*',
      '*://*.gogoanime.me/*',
      '*://*.gogoanime.vc/*',
      '*://*.kickassanime.am/*',
      '*://*.animeheaven.me/*',
      '*://*.animeid.tv/*',
      '*://*.animekhor.org/*',
      '*://*.animeko.co/*',
      '*://*.animenosub.to/*',
      '*://*.animetoast.cc/*',
      '*://*.animexin.vip/*',
      '*://*.animeav1.com/*',
      '*://*.aniyan.net/*',
      '*://*.moeclip.com/*',
      '*://*.adkami.com/*',
      '*://*.toonanime.cc/*',
      '*://*.topanimes.net/*',
      '*://*.kaguya.app/*',
      '*://*.luciferdonghua.in/*',
      '*://*.animepahe.com/*',
      // ── Community anime — ES/LATAM ────────────────────────────────────────
      '*://*.animeflv.net/*',
      '*://*.jkanime.net/*',
      '*://*.tioanime.com/*',
      '*://*.latanime.org/*',
      '*://*.monoschinos2.com/*',
      '*://*.animesonline.in/*',
      '*://*.otakustv.com/*',
      // ── Community anime — FR ──────────────────────────────────────────────
      '*://*.anime-sama.tv/*',
      '*://*.franime.fr/*',
      '*://*.french-anime.com/*',
      '*://*.voiranime.com/*',
      '*://*.otakufr.cc/*',
      // ── Community anime — PL ──────────────────────────────────────────────
      '*://*.anime-odcinki.pl/*',
      '*://*.frixysubs.pl/*',
      '*://*.fumetsu.pl/*',
      '*://*.docchi.pl/*',
      '*://*.ogladajanime.pl/*',
      '*://*.animezone.pl/*',
      '*://*.desu-online.pl/*',
      '*://*.shinden.pl/*',
      // ── Community anime — TR ──────────────────────────────────────────────
      '*://*.turkanime.co/*',
      '*://*.tranimeizle.net/*',
      '*://*.anizm.net/*',
      // ── Community anime — AR ──────────────────────────────────────────────
      '*://*.witanime.pics/*',
      '*://*.okanime.tv/*',
      // ── Community anime — RU/CIS ──────────────────────────────────────────
      '*://*.animego.me/*',
      '*://*.v3.animelib.org/*',
      '*://*.animebuff.ru/*',
      '*://*.sovetromantica.com/*',
      '*://*.animevost.org/*',
      '*://*.smotret-anime.org/*',
      '*://*.hdrezka.ag/*',
      // ── Community anime — PT/BR ───────────────────────────────────────────
      '*://*.betteranime.net/*',
      '*://*.animefire.net/*',
      '*://*.hinatasoul.com/*',
      // ── Community anime — IT ──────────────────────────────────────────────
      '*://*.animeworld.tv/*',
      '*://*.animeunity.it/*',
      // ── Community anime — DE ──────────────────────────────────────────────
      '*://*.aniworld.to/*',
      '*://*.bs.to/*',
      // ── Community anime — JP/EN ───────────────────────────────────────────
      '*://*.animelon.com/*',
      // Community manga
      '*://*.mangabat.com/*',
      '*://*.mangakakalot.com/*',
      '*://*.chapmanganato.to/*',
      '*://*.tcbscans.com/*',
      '*://*.tcbonepiecechapters.com/*',
      // Community manga (Aidoku)
      // Aidoku Community Sources
      '*://*.promanga.net/*', '*://*.silentquill.net/*', '*://*.batcave.biz/*', '*://*.comix.to/*', '*://*.flamecomics.xyz/*', '*://*.flamecomics.com/*',
      '*://*.hivetoons.org/*', '*://*.manga.madokami.al/*', '*://*.magustoon.org/*', '*://*.mangabats.com/*', '*://*.mangadistrict.com/*', '*://*.mangago.me/*',
      '*://*.mangakakalot.gg/*', '*://*.manganato.gg/*', '*://*.nelomanga.net/*', '*://*.mangaread.org/*', '*://*.mangasect.net/*', '*://*.mangatx.cc/*',
      '*://*.manhuagold.top/*', '*://*.manhuaplus.org/*', '*://*.manhwax.top/*', '*://*.novelbuddy.com/*', '*://*.nyxscans.com/*', '*://*.qiscans.org/*',
      '*://*.readcomiconline.li/*', '*://*.rizzfables.com/*', '*://*.tcbonepiecechapters.com/*', '*://*.toonily.com/*', '*://*.toonily.me/*', '*://*.vortexscans.org/*',
      '*://*.webtoon.xyz/*', '*://*.weebcentral.com/*', '*://*.mangafire.to/*', '*://*.nhentai.net/*', '*://*.cubari.moe/*', '*://*.xbat.si/*',
      '*://*.kanzenin.info/*', '*://*.komiksin.net/*', '*://*.komiktap.info/*', '*://*.01.komiku.asia/*', '*://*.mangasusuku.com/*', '*://*.manhwalist02.site/*',
      '*://*.natsu.tv/*', '*://*.bigsolo.org/*', '*://*.sushiscan.net/*', '*://*.catharsisworld.dig-it.info/*', '*://*.eternalmangas.org/*', '*://*.flowermanga.net/*',
      '*://*.mangalivre.tv/*', '*://*.hentailib.me/*', '*://*.mangalib.me/*', '*://*.ranobelib.me/*', '*://*.slashlib.me/*', '*://*.mangaworld.mx/*',
      '*://*.mangaworld.net/*', '*://*.comic-action.com/*', '*://*.comic-days.com/*', '*://*.manga.io.vn/*', '*://*.manga1000.top/*', '*://*.mangamura.net/*',
      '*://*.manga.nicovideo.jp/*', '*://*.raw1001.net/*', '*://*.rawfree.at/*', '*://*.rawkuma.net/*', '*://*.rawkuro.net/*', '*://*.rawotaku.com/*',
      '*://*.shonenjumpplus.com/*', '*://*.go-manga.com/*', '*://*.pretty-frank.com/*', '*://*.up-manga.com/*', '*://*.cmangax12.com/*', '*://*.cuutruyen.net/*',
      '*://*.dilib.vn/*', '*://*.foxtruyen2.com/*', '*://*.nettruyenviet1.com/*', '*://*.manhua3q.com/*', '*://*.truyenqqno.com/*', '*://*.truyenqq.online/*',
      '*://*.zettruyen.space/*', '*://*.baozimh.com/*', '*://*.bilimanga.net/*', '*://*.boylove.cc/*', '*://*.2026copy.com/*', '*://*.godamh.com/*',
      '*://*.happymh.com/*', '*://*.mangabz.com/*', '*://*.manhuagui.com/*', '*://*.mycomic.com/*', '*://*.manhuabika.com/*', '*://*.manga2026.com/*',
      '*://*.wnacg.com/*', '*://*.zaimanhua.com/*',
      // Legal manga
      '*://*.mangadex.org/*',
      '*://*.webtoons.com/*',
      '*://mangaplus.shueisha.co.jp/*',
    ],
  },
});
